language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hefayed/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hefayed/react-test npm test

after_success:
  - docker build -t multi-client ./client
  - docker build -t multi-nginx ./nginx
  - docker build -t multi-server ./server
  - docker build -t multi-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take images and push them to docker HUB
  - docker push hefayed/multi-docker:multi-client
  - docker push hefayed/multi-docker:multi-nginx
  - docker push hefayed/multi-docker:multi-server
  - docker push hefayed/multi-docker:multi-worker
